### ISSUE TITLE
Fix colab compatibility

### ISSUE THREAD

**Issue by mauicv** [mauicv/vaegan#5]
Test [here](https://colab.research.google.com/drive/14SJZDNANugSw0BytlHS81Vw-pl7mhiUQ#scrollTo=R_roWZSopiQ7)

**Comment by mauicv** [comment]
error:

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-11-d314b8c179c4>"](https://localhost:8080/#), line 1, in <module>
    from duct.utils.util_mixin import UtilsMixin

  File "/usr/local/lib/python3.7/dist-packages/duct/utils/util_mixin.py", line 2, in <module>
    from duct.model import ModelRegistry

  File "/usr/local/lib/python3.7/dist-packages/duct/model/__init__.py", line 1, in <module>
    from duct.model.autoencoders import NLLVarAutoEncoder, VarAutoEncoder, AutoEncoder

  File "/usr/local/lib/python3.7/dist-packages/duct/model/autoencoders.py", line 3, in <module>
    from duct.model.base_autoencoder import BaseAutoEncoder

  File "/usr/local/lib/python3.7/dist-packages/duct/model/base_autoencoder.py", line 33
    return self.decoder(out_z[0]), *out_z[1:]
                                   ^
SyntaxError: invalid syntax
```
